In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df = pd.read_csv("/home/train.csv")

In [2]:
# !pip install pandas

In [3]:
df.head(10)

id  sobreviveu  classe_social  \
0   1           0              3   
1   2           1              1   
2   3           1              3   
3   4           1              1   
4   5           0              3   
5   6           0              3   
6   7           0              1   
7   8           0              3   
8   9           1              3   
9  10           1              2   

                                                nome    sexo  idade  parentes  \
0                            Braund, Mr. Owen Harris    male   22.0         1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38.0         1   
2                             Heikkinen, Miss. Laina  female   26.0         0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35.0         1   
4                           Allen, Mr. William Henry    male   35.0         0   
5                                   Moran, Mr. James    male    NaN         0   
6                            McCarthy, Mr. Timothy J    male   54.0         0   
7                     Palsson, Master. Gosta Leonard    male    2.0         3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   27.0         0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female   14.0         1   

   dependentes           bilhete   tarifa cabine embarque  
0            0         A/5 21171   7.2500    NaN        S  
1            0          PC 17599  71.2833    C85        C  
2            0  STON/O2. 3101282   7.9250    NaN        S  
3            0            113803  53.1000   C123        S  
4            0            373450   8.0500    NaN        S  
5            0            330877   8.4583    NaN        Q  
6            0             17463  51.8625    E46        S  
7            1            349909  21.0750    NaN        S  
8            2            347742  11.1333    NaN        S  
9            0            237736  30.0708    NaN        C

In [4]:
#O conjunto de dados possui alguns campos nos quais não temos interesse prático,
#como, por exemplo, o nome e a identificaçao do bilhete.
df = df[["sobreviveu",
         "classe_social",
         "sexo",
         "idade",
         "parentes",
         "dependentes",
         "tarifa",
         "cabine",
         "embarque"]]
df.head(50)

sobreviveu  classe_social    sexo  idade  parentes  dependentes    tarifa  \
0            0              3    male   22.0         1            0    7.2500   
1            1              1  female   38.0         1            0   71.2833   
2            1              3  female   26.0         0            0    7.9250   
3            1              1  female   35.0         1            0   53.1000   
4            0              3    male   35.0         0            0    8.0500   
5            0              3    male    NaN         0            0    8.4583   
6            0              1    male   54.0         0            0   51.8625   
7            0              3    male    2.0         3            1   21.0750   
8            1              3  female   27.0         0            2   11.1333   
9            1              2  female   14.0         1            0   30.0708   
10           1              3  female    4.0         1            1   16.7000   
11           1              1  female   58.0         0            0   26.5500   
12           0              3    male   20.0         0            0    8.0500   
13           0              3    male   39.0         1            5   31.2750   
14           0              3  female   14.0         0            0    7.8542   
15           1              2  female   55.0         0            0   16.0000   
16           0              3    male    2.0         4            1   29.1250   
17           1              2    male    NaN         0            0   13.0000   
18           0              3  female   31.0         1            0   18.0000   
19           1              3  female    NaN         0            0    7.2250   
20           0              2    male   35.0         0            0   26.0000   
21           1              2    male   34.0         0            0   13.0000   
22           1              3  female   15.0         0            0    8.0292   
23           1              1    male   28.0         0            0   35.5000   
24           0              3  female    8.0         3            1   21.0750   
25           1              3  female   38.0         1            5   31.3875   
26           0              3    male    NaN         0            0    7.2250   
27           0              1    male   19.0         3            2  263.0000   
28           1              3  female    NaN         0            0    7.8792   
29           0              3    male    NaN         0            0    7.8958   
30           0              1    male   40.0         0            0   27.7208   
31           1              1  female    NaN         1            0  146.5208   
32           1              3  female    NaN         0            0    7.7500   
33           0              2    male   66.0         0            0   10.5000   
34           0              1    male   28.0         1            0   82.1708   
35           0              1    male   42.0         1            0   52.0000   
36           1              3    male    NaN         0            0    7.2292   
37           0              3    male   21.0         0            0    8.0500   
38           0              3  female   18.0         2            0   18.0000   
39           1              3  female   14.0         1            0   11.2417   
40           0              3  female   40.0         1            0    9.4750   
41           0              2  female   27.0         1            0   21.0000   
42           0              3    male    NaN         0            0    7.8958   
43           1              2  female    3.0         1            2   41.5792   
44           1              3  female   19.0         0            0    7.8792   
45           0              3    male    NaN         0            0    8.0500   
46           0              3    male    NaN         1            0   15.5000   
47           1              3  female    NaN         0            0    7.7500   
48           0              3    ma

In [5]:
#A variável-alvo é saber se o passageiro em questão sobreviveu ao acidente, isto é, o
#campo sobreviveu. Vamos separar esse campo do restante do conjunto de dados
labels = df.sobreviveu
labels.head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: sobreviveu, dtype: int64

In [6]:
'''
Outro ponto para nos preocuparmos é com quais colunas podemos contar. Ou seja, será
que temos valores adequados em todas as colunas? Podemos ver com muita facilidade
que a coluna cabine tem uma quantidade considerável de valores ausentes, que nos
conjuntos de dados está identificado como NaN (not a number). Vamos avaliar as
colunas medindo o percentual de indefinições:
'''
#localiza todos as linhas cujos valores não são números na coluna classe
# e imprime a tupla que mostra a dimensão
df.loc[     pd.isna(df['classe_social']), 'classe_social'    ].shape


(0,)

In [7]:
'''
A boa notícia é que não temos nenhum valor indefinido na coluna classe, então não
precisamos fazer nada com ela
'''

df.loc[pd.isna(df['sexo']), 'sexo'].shape

(0,)

In [8]:

df.loc[pd.isna(df['idade']), 'idade'].shape

(177,)

In [9]:
'''
Aqui já temos um problema, a coluna idade possui 177 valores indefinidos.
Dividindo pelo número total de itens nessa coluna, saberemos o percentual de valores
problemáticos
'''
indefinidos_idade = df.loc[pd.isna(df['idade']), 'idade'].shape[0]#pega o valor 177
total = df.idade.shape[0]
print("Total: ", total)
print((indefinidos_idade/total)*100)

Total:  891
19.865319865319865


In [10]:
'''
Temos 19% dos dados comprometidos apenas pelo campo coluna. Vamos prosseguir
com a análise e avaliar os demais campos. Mas para evitar uma tarefa repetitiva, vamos
criar uma função para isso
'''
def calcula_percentual_indefinido(dataframe, coluna ):
    indefinidos = dataframe.loc[pd.isna(dataframe[coluna]), coluna].shape[0]
    #total = dataframe.idade.shape[0]
    total = dataframe[coluna].shape[0]

    return (indefinidos/total)* 100

In [11]:
calcula_percentual_indefinido(df, 'parentes')

0.0

In [12]:
calcula_percentual_indefinido(df, 'dependentes')

0.0

In [13]:
calcula_percentual_indefinido(df, 'tarifa')

0.0

In [14]:
calcula_percentual_indefinido(df, 'cabine')

77.10437710437711

In [15]:
calcula_percentual_indefinido(df, 'embarque')

0.22446689113355783

In [16]:
'''
Os campos em que temos problemas são:
» idade (19.87%).
» cabine (77.10%)#DROOOOOOOOOOP NA COLUNA
» embarque (0.22%).
'''
'''
O campo cabine é o que mais compromete: 77,10% é muito! Em lugar de corrigir esses
dados é melhor assumir que simplesmente não possuímos essa informação e excluí-la
do nosso conjunto de dados
'''
df = df.drop('cabine', axis=1)
#df = df.drop(columns=['cabine'])
df.head(10)

sobreviveu  classe_social    sexo  idade  parentes  dependentes   tarifa  \
0           0              3    male   22.0         1            0   7.2500   
1           1              1  female   38.0         1            0  71.2833   
2           1              3  female   26.0         0            0   7.9250   
3           1              1  female   35.0         1            0  53.1000   
4           0              3    male   35.0         0            0   8.0500   
5           0              3    male    NaN         0            0   8.4583   
6           0              1    male   54.0         0            0  51.8625   
7           0              3    male    2.0         3            1  21.0750   
8           1              3  female   27.0         0            2  11.1333   
9           1              2  female   14.0         1            0  30.0708   

  embarque  
0        S  
1        C  
2        S  
3        S  
4        S  
5        Q  
6        S  
7        S  
8        S  
9        C

In [17]:
'''
O campo idade tem problemas em quase 20% dos casos, e não é simples definir um
valor-padrão. A primeira ideia seria assumir que os campos sem idade poderiam
receber o valor zero, mas isso pode comprometer muito o trabalho criando um desvio
para idades mais baixas. A segunda ideia é excluir esses dados; nesse caso, teremos um
dataset um pouco menor, mas que pode funcionar melhor, se não funcionar, aí então
nos preocupamos
'''

#deleta todas as linhas cujos números não são valores válidos
df = df[np.isfinite(df['idade'])] 
df.head(50)

sobreviveu  classe_social    sexo  idade  parentes  dependentes    tarifa  \
0            0              3    male   22.0         1            0    7.2500   
1            1              1  female   38.0         1            0   71.2833   
2            1              3  female   26.0         0            0    7.9250   
3            1              1  female   35.0         1            0   53.1000   
4            0              3    male   35.0         0            0    8.0500   
6            0              1    male   54.0         0            0   51.8625   
7            0              3    male    2.0         3            1   21.0750   
8            1              3  female   27.0         0            2   11.1333   
9            1              2  female   14.0         1            0   30.0708   
10           1              3  female    4.0         1            1   16.7000   
11           1              1  female   58.0         0            0   26.5500   
12           0              3    male   20.0         0            0    8.0500   
13           0              3    male   39.0         1            5   31.2750   
14           0              3  female   14.0         0            0    7.8542   
15           1              2  female   55.0         0            0   16.0000   
16           0              3    male    2.0         4            1   29.1250   
18           0              3  female   31.0         1            0   18.0000   
20           0              2    male   35.0         0            0   26.0000   
21           1              2    male   34.0         0            0   13.0000   
22           1              3  female   15.0         0            0    8.0292   
23           1              1    male   28.0         0            0   35.5000   
24           0              3  female    8.0         3            1   21.0750   
25           1              3  female   38.0         1            5   31.3875   
27           0              1    male   19.0         3            2  263.0000   
30           0              1    male   40.0         0            0   27.7208   
33           0              2    male   66.0         0            0   10.5000   
34           0              1    male   28.0         1            0   82.1708   
35           0              1    male   42.0         1            0   52.0000   
37           0              3    male   21.0         0            0    8.0500   
38           0              3  female   18.0         2            0   18.0000   
39           1              3  female   14.0         1            0   11.2417   
40           0              3  female   40.0         1            0    9.4750   
41           0              2  female   27.0         1            0   21.0000   
43           1              2  female    3.0         1            2   41.5792   
44           1              3  female   19.0         0            0    7.8792   
49           0              3  female   18.0         1            0   17.8000   
50           0              3    male    7.0         4            1   39.6875   
51           0              3    male   21.0         0            0    7.8000   
52           1              1  female   49.0         1            0   76.7292   
53           1              2  female   29.0         1            0   26.0000   
54           0              1    male   65.0         0            1   61.9792   
56           1              2  female   21.0         0            0   10.5000   
57           0              3    male   28.5         0            0    7.2292   
58           1              2  female    5.0         1            2   27.7500   
59           0              3    male   11.0         5            2   46.9000   
60           0              3    male   22.0         0            0    7.2292   
61           1              1  female   38.0         0            0   80.0000   
62           0              1    male   45.0         1            0   83.4750   
63           0              3    ma

In [18]:
'''
O que fizemos acima foi excluir todos os registros que não possuem valores válidos na
coluna idade. Se calcularmos agora o percentual indefinido na coluna idade teremos:
'''
calcula_percentual_indefinido(df, 'idade')

0.0

In [19]:
'''
A coluna embarque é a menos problemática, menos de 0,5% dos valores está
indefinido. Vamos excluir os registros problemáticos sem nos preocupar muito com a
interferência.
'''
df = df[ ~pd.isna(df.embarque)] #dataframe recebe todos os que são número diferentes de NaN
calcula_percentual_indefinido(df, 'embarque')

0.0

In [20]:
#teste definição dados categóricos

def dados_categóricos(df):
  for coluna in df:
    dados = df[coluna].unique()
    if len(dados) < 20:
      print(coluna)

dados_categóricos(df)

sobreviveu
classe_social
sexo
parentes
dependentes
embarque


In [21]:
'''
Pronto, agora que limpamos todos os pontos estranhos, precisamos converter os
campos categóricos em one-hot; são eles: classe, sexo e embarque. Para analisá-los,
vamos começar obtendo os valores que podem assumir:
'''
df.classe_social.unique()

array([3, 1, 2])

In [22]:
'''
Isso quer dizer que um passageiro pode ter sido alocado na primeira, segunda ou
terceira classes. Computacionalmente esse tipo de categoria é muito ruim, porque é
comparável! Sabemos que esses campos estão ordenados e não deveriam; então vamos
mapear cada uma dessas classes para vetores. Para facilitar, vamos criar uma função
que faça isso para nós:
'''

def one_hot(categorias, valor):
# Transforma as categorias num conjunto para eliminar duplicatas,
# depois transforma em lista para obter índice
    categorias = list(set(categorias))
    print("Categorias: ")
    print(categorias)
# Obtém o índice do elemento atual
    indice = categorias.index(valor)
    print("Indice ")
    print(indice)
# Cria um vetor com o número de coordenadas igual ao número de categorias
    print("Vetor")
    vetor = np.zeros(len(categorias))
# Modifica o índice correspondente a classe para 1.0 no vetor de categorias
    vetor[indice] = 1.0
# devolve o vetor one-hot resultante
    return vetor

In [23]:
# onehot_encoder = OneHotEncoder(sparse=False) #sparse=False gera matriz de vetores
# vetores_binarios = onehot_encoder.fit_transform(np.array(df.classe_social).reshape(len(df.classe_social),1))
# vetores_binarios

In [24]:
one_hot(df.classe_social, 1)

Categorias: 
[1, 2, 3]
Indice 
0
Vetor


array([1., 0., 0.])

In [25]:
one_hot(df.classe_social, 2)

Categorias: 
[1, 2, 3]
Indice 
1
Vetor


array([0., 1., 0.])

In [26]:
one_hot(df.classe_social, 3)

Categorias: 
[1, 2, 3]
Indice 
2
Vetor


array([0., 0., 1.])

In [27]:
'''
Da mesma forma, vamos observar que a coluna sexo é feita de palavras, o que é inútil do
ponto de vista da inteligência artificial. Vamos converter para vetores one-hot usando a
função anterior. Primeiro, vejamos os valores possíveis:
'''
df.sexo.unique()

array(['male', 'female'], dtype=object)

In [28]:
print(one_hot(df.sexo, 'male'))
print(one_hot(df.sexo, 'female'))

Categorias: 
['female', 'male']
Indice 
1
Vetor
[0. 1.]
Categorias: 
['female', 'male']
Indice 
0
Vetor
[1. 0.]


In [29]:
'''
Agora faremos o mesmo com a coluna embarque.
Vejamos quais os valores possíveis
'''
df.embarque.unique()

array(['S', 'C', 'Q'], dtype=object)

In [30]:
one_hot(df.embarque, 'S')

Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor


array([1., 0., 0.])

In [31]:
one_hot(df.embarque, 'C')

Categorias: 
['S', 'Q', 'C']
Indice 
2
Vetor


array([0., 0., 1.])

In [32]:
one_hot(df.embarque, 'Q')

Categorias: 
['S', 'Q', 'C']
Indice 
1
Vetor


array([0., 1., 0.])

In [33]:
#Agora vamos transformar as colunas de acordo com a codificação one-hot
df.classe_social = [  one_hot(df.classe_social, _) for _ in df.classe_social   ]

Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
1
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
1
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
1
Vetor
Categorias: 
[1, 2, 3]
Indice 
1
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
2
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
Indice 
0
Vetor
Categorias: 
[1, 2, 3]
In

In [34]:
df.head(10)

sobreviveu    classe_social    sexo  idade  parentes  dependentes  \
0            0  [0.0, 0.0, 1.0]    male   22.0         1            0   
1            1  [1.0, 0.0, 0.0]  female   38.0         1            0   
2            1  [0.0, 0.0, 1.0]  female   26.0         0            0   
3            1  [1.0, 0.0, 0.0]  female   35.0         1            0   
4            0  [0.0, 0.0, 1.0]    male   35.0         0            0   
6            0  [1.0, 0.0, 0.0]    male   54.0         0            0   
7            0  [0.0, 0.0, 1.0]    male    2.0         3            1   
8            1  [0.0, 0.0, 1.0]  female   27.0         0            2   
9            1  [0.0, 1.0, 0.0]  female   14.0         1            0   
10           1  [0.0, 0.0, 1.0]  female    4.0         1            1   

     tarifa embarque  
0    7.2500        S  
1   71.2833        C  
2    7.9250        S  
3   53.1000        S  
4    8.0500        S  
6   51.8625        S  
7   21.0750        S  
8   11.1333        S  
9   30.0708        C  
10  16.7000        S

In [35]:
df.sexo = [one_hot(df.sexo, _) for _ in df.sexo]

Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
1
Vetor
Categorias: 
['female', 'male']
Indice 
0
Vetor
Categorias: 
['female', 'male']
Indice 


In [36]:
df.head()

sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0           0  [0.0, 0.0, 1.0]  [0.0, 1.0]   22.0         1            0   
1           1  [1.0, 0.0, 0.0]  [1.0, 0.0]   38.0         1            0   
2           1  [0.0, 0.0, 1.0]  [1.0, 0.0]   26.0         0            0   
3           1  [1.0, 0.0, 0.0]  [1.0, 0.0]   35.0         1            0   
4           0  [0.0, 0.0, 1.0]  [0.0, 1.0]   35.0         0            0   

    tarifa embarque  
0   7.2500        S  
1  71.2833        C  
2   7.9250        S  
3  53.1000        S  
4   8.0500        S

In [37]:
df.embarque = [one_hot(df.embarque, _) for _ in df.embarque]
df.head()

Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
2
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
2
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
1
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
1
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias: 
['S', 'Q', 'C']
Indice 
0
Vetor
Categorias

sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0           0  [0.0, 0.0, 1.0]  [0.0, 1.0]   22.0         1            0   
1           1  [1.0, 0.0, 0.0]  [1.0, 0.0]   38.0         1            0   
2           1  [0.0, 0.0, 1.0]  [1.0, 0.0]   26.0         0            0   
3           1  [1.0, 0.0, 0.0]  [1.0, 0.0]   35.0         1            0   
4           0  [0.0, 0.0, 1.0]  [0.0, 1.0]   35.0         0            0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [38]:
'''
Não podemos nos esquecer de codificar também os resultados finais! A sobrevivência
ou não do passageiro, as classes finais armazenadas na coluna labels que separamos do
conjunto de dados, precisa ser codificada também. Primeiro, vejamos os valores possíveis:
'''
df.sobreviveu.unique()


array([0, 1])

In [39]:
df.sobreviveu = [one_hot(df.sobreviveu, _) for _ in df.sobreviveu]
df.head(10)

Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
1
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 
0
Vetor
Categorias: 
[0, 1]
Indice 


sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0   [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]   22.0         1            0   
1   [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]   38.0         1            0   
2   [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]   26.0         0            0   
3   [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]   35.0         1            0   
4   [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]   35.0         0            0   
6   [1.0, 0.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]   54.0         0            0   
7   [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]    2.0         3            1   
8   [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]   27.0         0            2   
9   [0.0, 1.0]  [0.0, 1.0, 0.0]  [1.0, 0.0]   14.0         1            0   
10  [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]    4.0         1            1   

     tarifa         embarque  
0    7.2500  [1.0, 0.0, 0.0]  
1   71.2833  [0.0, 0.0, 1.0]  
2    7.9250  [1.0, 0.0, 0.0]  
3   53.1000  [1.0, 0.0, 0.0]  
4    8.0500  [1.0, 0.0, 0.0]  
6   51.8625  [1.0, 0.0, 0.0]  
7   21.0750  [1.0, 0.0, 0.0]  
8   11.1333  [1.0, 0.0, 0.0]  
9   30.0708  [0.0, 0.0, 1.0]  
10  16.7000  [1.0, 0.0, 0.0]

In [40]:
'''
O próximo passo é normalizar os valores escalares. Vamos normalizar pela média, isto
é, vamos aplicar a seguinte transformação:

  Xnovo = (Xatual - Xmédio)/ (Xmax - Xmin)

'''
def normaliza_media(valores):
    media = np.mean(valores)
    minimo = np.min(valores)
    maximo = np.max(valores)
    return (valores - media)/(maximo-minimo)

In [41]:
df.idade = normaliza_media(df.idade)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0] -0.096030         1            0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.105025         1            0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0] -0.045766         0            0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.067327         1            0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.067327         0            0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [42]:
df.parentes = normaliza_media(df.parentes)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0] -0.096030  0.097191            0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.105025  0.097191            0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0] -0.045766 -0.102809            0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.067327  0.097191            0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.067327 -0.102809            0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [43]:
df.dependentes = normaliza_media(df.dependentes)
df.dependentes.head(10)

0    -0.072097
1    -0.072097
2    -0.072097
3    -0.072097
4    -0.072097
6    -0.072097
7     0.094569
8     0.261236
9    -0.072097
10    0.094569
Name: dependentes, dtype: float64

In [44]:
df.tarifa = normaliza_media(df.tarifa)
df.tarifa.head(10)

0    -0.053320
1     0.071665
2    -0.052002
3     0.036174
4    -0.051758
6     0.033758
7    -0.026335
8    -0.045740
9    -0.008776
10   -0.034875
Name: tarifa, dtype: float64

In [45]:
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0] -0.096030  0.097191    -0.072097   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.105025  0.097191    -0.072097   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [1.0, 0.0] -0.045766 -0.102809    -0.072097   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]  0.067327  0.097191    -0.072097   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.067327 -0.102809    -0.072097   

     tarifa         embarque  
0 -0.053320  [1.0, 0.0, 0.0]  
1  0.071665  [0.0, 0.0, 1.0]  
2 -0.052002  [1.0, 0.0, 0.0]  
3  0.036174  [1.0, 0.0, 0.0]  
4 -0.051758  [1.0, 0.0, 0.0]

In [46]:
'''
Agora podemos separar o vetor de classificação do restante do conjunto de dados.
'''
labels = df.sobreviveu.values

In [47]:
'''
E apagar a coluna do conjunto de dados.
'''
df = df.drop(['sobreviveu'], axis=1)
df.head(10)

classe_social        sexo     idade  parentes  dependentes    tarifa  \
0   [0.0, 0.0, 1.0]  [0.0, 1.0] -0.096030  0.097191    -0.072097 -0.053320   
1   [1.0, 0.0, 0.0]  [1.0, 0.0]  0.105025  0.097191    -0.072097  0.071665   
2   [0.0, 0.0, 1.0]  [1.0, 0.0] -0.045766 -0.102809    -0.072097 -0.052002   
3   [1.0, 0.0, 0.0]  [1.0, 0.0]  0.067327  0.097191    -0.072097  0.036174   
4   [0.0, 0.0, 1.0]  [0.0, 1.0]  0.067327 -0.102809    -0.072097 -0.051758   
6   [1.0, 0.0, 0.0]  [0.0, 1.0]  0.306081 -0.102809    -0.072097  0.033758   
7   [0.0, 0.0, 1.0]  [0.0, 1.0] -0.347350  0.497191     0.094569 -0.026335   
8   [0.0, 0.0, 1.0]  [1.0, 0.0] -0.033200 -0.102809     0.261236 -0.045740   
9   [0.0, 1.0, 0.0]  [1.0, 0.0] -0.196558  0.097191    -0.072097 -0.008776   
10  [0.0, 0.0, 1.0]  [1.0, 0.0] -0.322218  0.097191     0.094569 -0.034875   

           embarque  
0   [1.0, 0.0, 0.0]  
1   [0.0, 0.0, 1.0]  
2   [1.0, 0.0, 0.0]  
3   [1.0, 0.0, 0.0]  
4   [1.0, 0.0, 0.0]  
6   [1.0, 0.0, 0.0]  
7   [1.0, 0.0, 0.0]  
8   [1.0, 0.0, 0.0]  
9   [0.0, 0.0, 1.0]  
10  [1.0, 0.0, 0.0]

In [48]:
'''
Agora precisamos transformar esse conjunto de dados em vetores, esses vetores, o que
na prática, é concatenar as colunas. Vamos criar uma função para isso:
'''
def vetorizar(classe_social, sexo, idade, parentes, dependentes, tarifa, embarque):
    return classe_social.tolist() + sexo.tolist() + [idade] + [parentes] + [dependentes] + [tarifa] + embarque.tolist()

entrada = [vetorizar(*_) for _ in df.values]

In [49]:
entrada = [vetorizar(*_) for _ in df.values]

In [50]:

def f():
    return (1,2,3,4)

a,b,c,d = f()
print(a)

1


In [51]:
a, b, c,d = f()

In [52]:
a, *_ = f()
print(a)
print(_)

1
[2, 3, 4]


In [53]:
entrada[:10]

[[0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  -0.09603031787671788,
  0.09719101123595505,
  -0.07209737827715355,
  -0.053319723733283836,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.10502522371664728,
  0.09719101123595505,
  -0.07209737827715355,
  0.0716649540871488,
  0.0,
  0.0,
  1.0],
 [0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  -0.04576643247837659,
  -0.10280898876404494,
  -0.07209737827715355,
  -0.05200221147749205,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.06732730966789131,
  0.09719101123595505,
  -0.07209737827715355,
  0.03617351616012845,
  1.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.06732730966789131,
  -0.10280898876404494,
  -0.07209737827715355,
  -0.0517582277264195,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.30608076531001244,
  -0.10280898876404494,
  -0.07209737827715355,
  0.03375807702451017,
  1.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  -0.34734974486842435,
  0.49719101123595505,
  0.0945692

In [54]:
'''
Finalmente, temos os dados prontos para usar como entrada em algoritmos de
classificação. Vamos salvar os dados resultantes para usar mais tarde.
'''
np.savetxt("/home/entrada_treino.csv", entrada, delimiter=',')

In [55]:
np.savetxt("/home/labels.csv", labels.tolist(), delimiter=',')

In [56]:
import warnings
warnings.filterwarnings('ignore')



In [57]:
'''
Aqui vamos criar um modelo baseado no conjunto de vizinhos mais próximos. Vamos
usar a biblioteca scikitlearn, ela possui algumas implementações do algoritmo. O
primeiro passo é importar o que vamos precisar para o trabalho.
'''
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
#from bokeh.plotting import figure, show, output_notebook

In [58]:
x = np.loadtxt("/home/entrada_treino.csv", delimiter=',')
y = np.loadtxt("/home/labels.csv", delimiter=',')

In [59]:
y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [60]:
#cria um modelo para classificação usando KNN com k=5
model = KNeighborsClassifier(n_neighbors=5)

In [61]:
'''
Com o modelo criado, o treinamento é simples, basta usar a função fit referenciando os
vetores de entrada e os vetores com a classe selecionada. Vamos separar 70% dos dados
para treino e os outros 30% para validação. Primeiro, descobrimos quanto é 70% dos
dados de treino:
'''
tamanho_treino = int(x.shape[0]*0.7)
tamanho_treino


498

In [62]:
x.shape[0] #linhas

712

In [63]:
x

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [64]:
x.shape[1] #colunas

12

In [65]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=30)

In [66]:
#Agora o que fazemos é separar para treino os dados até o índice tamanho_treino:

x_teste = x[:tamanho_treino]
y_teste = y[:tamanho_treino]

In [67]:
#Agora separamos a partir de tamanho_treino para validação
x_validacao = x[tamanho_treino:]
y_validacao = y[tamanho_treino:]

In [68]:
#Agora criamos o modelo usando os dados de treino.
model.fit(X_train, y_train)

KNeighborsClassifier()

In [77]:
'''
Vamos avaliar como o modelo performa nos dados de validação, ou seja, nos dados que
ele ainda não conhece.
'''
model.score(X_test, y_test)

0.8411214953271028

In [70]:
cores = ['preto', 'preto', 'azul', 'vermelho', 'azul', 'rosa']

#Aplicando label_encoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
valores_numericos = label_encoder.fit_transform(cores)
print(valores_numericos)

[1 1 0 3 0 2]


In [71]:
set(valores_numericos)

{0, 1, 2, 3}

In [72]:
#One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False) #sparse=False gera matriz de vetores

# transforma a lista de valores em uma lista de 1 dimensão
inteiros = valores_numericos.reshape(len(valores_numericos),1)
inteiros

array([[1],
       [1],
       [0],
       [3],
       [0],
       [2]])

In [73]:
#Passa os valores para o objeto onehot_encoder fazer a transformação.
vetores_binarios = onehot_encoder.fit_transform(inteiros)
print(cores)
print("_______________________________________________")
print(vetores_binarios)

['preto', 'preto', 'azul', 'vermelho', 'azul', 'rosa']
_______________________________________________
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [74]:
from numpy import NaN
import pandas as pd

matrix = pd.DataFrame([1,2,3,4,NaN], columns=['Number'], dtype='float64')
# Remove NaN in column 'Number'
matrix['Number'][~matrix['Number'].isnull()]

0    1.0
1    2.0
2    3.0
3    4.0
Name: Number, dtype: float64